services:
  db:
    image: mysql
    restart: always
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - phpmyadmin_mysql_volume:/var/lib/mysql  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: my_phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=my_db:3306
    volumes:
      - ./mysql/script:/scripts
    depends_on:
      - db
    #entrypoint: ["/bin/bash", "-c", "/scripts/data.sh"]

volumes:
  phpmyadmin_mysql_volume: