services:
  db:
    image: mysql
    restart: always
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - phpmyadmin_connect_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: my_phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=my_db:3306


volumes:
  phpmyadmin_connect_volume: